/**
 * @file verticx-backend/src/services/database.ts
 * @description Simulates a persistent database layer and initializes mock data.
 */
import type * as Api from "../types/api";

export let db: { [key: string]: any[] } = {};

export const saveDb = () => {
  // In a Node.js mock environment, this is a no-op. Data persists in memory.
};

const ALL_FEATURES = {
  principal_students: true,
  principal_faculty: true,
  principal_classes: true,
  principal_finance: true,
  principal_attendance: true,
  principal_results: true,
  principal_staff_requests: true,
  principal_grievances: true,
  principal_events: true,
  principal_communication: true,
  principal_reports: true,
  principal_profile: true,
  principal_complaints: true,
  registrar_admissions: true,
  registrar_academic_requests: true,
  registrar_students: true,
  registrar_faculty: true,
  registrar_classes: true,
  registrar_fees: true,
  registrar_attendance: true,
  registrar_timetable: true,
  registrar_library: true,
  registrar_hostel: true,
  registrar_transport: true,
  registrar_inventory: true,
  registrar_documents: true,
  registrar_events: true,
  registrar_reports: true,
  registrar_communication: true,
  registrar_bulk_movement: true,
  teacher_attendance: true,
  teacher_gradebook: true,
  teacher_quizzes: true,
  teacher_syllabus: true,
  teacher_content: true,
  student_syllabus: true,
  student_content: true,
  student_assignments: true,
  student_grades: true,
  student_attendance: true,
  student_feedback: true,
  student_complaints: true,
  student_ask_ai: true,
  parent_academics: true,
  parent_fees: true,
  parent_complaints: true,
  parent_contact_teacher: true,
  online_payments_enabled: true,
  erp_billing_enabled: true,
};

const ALL_DB_KEYS = [
  "branches",
  "users",
  "parents",
  "students",
  "teachers",
  "subjects",
  "schoolClasses",
  "courses",
  "feeTemplates",
  "timetableConfigs",
  "timetable",
  "grades",
  "assignments",
  "attendance",
  "teacherAttendance",
  "feePayments",
  "feeAdjustments",
  "feeRecords",
  "syllabusProgress",
  "suspensionRecords",
  "libraryBooks",
  "bookIssuances",
  "registrationRequests",
  "applications",
  "announcements",
  "complaintsAboutStudents",
  "teacherComplaints",
  "lectures",
  "leaveApplications",
  "quizzes",
  "quizQuestions",
  "studentQuizzes",
  "studentAnswers",
  "meetingRequests",
  "facultyApplications",
  "schoolDocuments",
  "schoolEvents",
  "transportRoutes",
  "hostels",
  "rooms",
  "inventoryItems",
  "inventoryLogs",
  "concessionRequests",
  "smsHistory",
  "rectificationRequests",
  "courseContent",
  "teacherFeedback",
  "syllabusChangeRequests",
  "adminSmsHistory",
  "adminEmailHistory",
  "adminNotificationHistory",
  "examinations",
  "examSchedules",
  "examMarks",
  "examMarkRectificationRequests",
  "skillAssessments",
  "markingTemplates",
  "studentMarks",
  "systemSettings",
  "teacherAttendanceRectificationRequests",
  "feeRectificationRequests",
  "leaveSettings",
  "archivedStudentRecords",
  "manualExpenses",
  "manualSalaryAdjustments",
  "payrollRecords",
  "erpPayments",
  "auditLogs",
  "principalQueries",
  "studentSyllabusProgress",
];

const initializeMockData = () => {
  for (const key of ALL_DB_KEYS) {
    db[key] = [];
  }
  const mockData = {
    users: [
      {
        id: "superadmin",
        name: "Super Admin",
        email: "superadmin@verticx.com",
        role: "SuperAdmin",
        password: "superadmin123",
        phone: "9876543210",
      },
      {
        id: "admin-1",
        name: "Admin User",
        email: "admin@verticx.com",
        role: "Admin",
        password: "admin123",
      },
      {
        id: "principal-1",
        name: "Dr. Evelyn Reed",
        email: "principal.north@verticx.com",
        role: "Principal",
        password: "principal123",
        branchId: "branch-north",
        phone: "9876543211",
        salary: 120000,
        leaveBalances: { sick: 12, casual: 10 },
      },
      {
        id: "principal-2",
        name: "Mr. Alan Grant",
        email: "principal.south@verticx.com",
        role: "Principal",
        password: "principal123",
        branchId: "branch-south",
        salary: 115000,
        leaveBalances: { sick: 12, casual: 10 },
      },
      {
        id: "VRTX-REG-001",
        name: "Robert Muldoon",
        email: "registrar.north@verticx.com",
        role: "Registrar",
        password: "registrar123",
        branchId: "branch-north",
        salary: 60000,
        leaveBalances: { sick: 12, casual: 10 },
      },
      {
        id: "VRTX-TCH-001",
        name: "Dr. Ian Malcolm",
        email: "ian.malcolm@verticx.com",
        role: "Teacher",
        password: "teacher123",
        branchId: "branch-north",
        salary: 75000,
        leaveBalances: { sick: 12, casual: 10, earned: 15 },
      },
      {
        id: "VRTX-TCH-002",
        name: "Ellie Sattler",
        email: "ellie.sattler@verticx.com",
        role: "Teacher",
        password: "teacher123",
        branchId: "branch-north",
        salary: 72000,
        leaveBalances: { sick: 12, casual: 10, earned: 15 },
      },
      {
        id: "VRTX-STU-0001",
        name: "Alex Murphy",
        email: "alex.murphy@student.verticx.com",
        role: "Student",
        password: "student123",
        branchId: "branch-north",
      },
      {
        id: "parent-1",
        name: "Sarah Connor",
        email: "parent.sarah@verticx.com",
        role: "Parent",
        password: "parent123",
        childrenIds: ["VRTX-STU-0001"],
      },
      {
        id: "VRTX-LIB-001",
        name: "Barbara Gordon",
        email: "librarian.north@verticx.com",
        role: "Librarian",
        password: "librarian123",
        branchId: "branch-north",
        salary: 45000,
        leaveBalances: { sick: 12, casual: 10 },
      },
    ],
    branches: [
      {
        id: "branch-north",
        registrationId: "SCH-N-01",
        name: "North Branch",
        location: "City North, State",
        principalId: "principal-1",
        registrarId: "VRTX-REG-001",
        status: "active",
        email: "north@verticx.com",
        helplineNumber: "123-456-7890",
        erpPricePerStudent: 10,
        billingCycle: "monthly",
        nextDueDate: new Date(
          new Date().getFullYear(),
          new Date().getMonth() + 1,
          10
        )
          .toISOString()
          .split("T")[0],
        enabledFeatures: { ...ALL_FEATURES },
        academicSessionStartDate: "2024-04-01",
        paymentGatewayPublicKey: "rzp_test_ILgsfZC32z1234",
        stats: {
          students: 1,
          teachers: 2,
          staff: 4,
          healthScore: 92.5,
          avgPerformance: 85.0,
          feeDefaulters: 1,
        },
      },
      {
        id: "branch-south",
        registrationId: "SCH-S-02",
        name: "South Branch",
        location: "City South, State",
        principalId: "principal-2",
        status: "active",
        email: "south@verticx.com",
        helplineNumber: "123-456-7891",
        erpPricePerStudent: 12,
        billingCycle: "monthly",
        nextDueDate: new Date(
          new Date().getFullYear(),
          new Date().getMonth() + 1,
          10
        )
          .toISOString()
          .split("T")[0],
        enabledFeatures: { ...ALL_FEATURES },
        academicSessionStartDate: "2024-04-01",
        stats: {
          students: 0,
          teachers: 0,
          staff: 1,
          healthScore: 95.0,
          avgPerformance: 88.0,
          feeDefaulters: 0,
        },
      },
    ],
    parents: [
      { id: "parent-1", name: "Sarah Connor", childrenIds: ["VRTX-STU-0001"] },
    ],
    students: [
      {
        id: "VRTX-STU-0001",
        branchId: "branch-north",
        name: "Alex Murphy",
        gradeLevel: 10,
        parentId: "parent-1",
        classId: "class-10a-north",
        status: "active",
        dob: "2008-05-15",
        address: "123 Cyber Street",
        gender: "Male",
        guardianInfo: {
          name: "Sarah Connor",
          email: "parent.sarah@verticx.com",
          phone: "555-0101",
        },
        schoolRank: 15,
        rollNo: "10A-01",
        leaveBalances: { sick: 10, planned: 5 },
      },
    ],
    teachers: [
      {
        id: "VRTX-TCH-001",
        branchId: "branch-north",
        name: "Dr. Ian Malcolm",
        subjectIds: ["sub-math-10", "sub-cs-10"],
        qualification: "PhD Mathematics",
        doj: "2020-08-01",
        gender: "Male",
        email: "ian.malcolm@verticx.com",
        phone: "555-0201",
        status: "active",
        salary: 75000,
        leaveBalances: { sick: 12, casual: 10, earned: 15 },
      },
      {
        id: "VRTX-TCH-002",
        branchId: "branch-north",
        name: "Ellie Sattler",
        subjectIds: ["sub-bio-10"],
        qualification: "PhD Paleobotany",
        doj: "2019-07-15",
        gender: "Female",
        email: "ellie.sattler@verticx.com",
        phone: "555-0202",
        status: "active",
        salary: 72000,
        leaveBalances: { sick: 12, casual: 10, earned: 15 },
      },
    ],
    subjects: [
      {
        id: "sub-math-10",
        branchId: "branch-north",
        name: "Mathematics G10",
        teacherId: "VRTX-TCH-001",
      },
      {
        id: "sub-cs-10",
        branchId: "branch-north",
        name: "Computer Science G10",
        teacherId: "VRTX-TCH-001",
      },
      {
        id: "sub-bio-10",
        branchId: "branch-north",
        name: "Biology G10",
        teacherId: "VRTX-TCH-002",
      },
    ],
    schoolClasses: [
      {
        id: "class-10a-north",
        branchId: "branch-north",
        gradeLevel: 10,
        section: "A",
        subjectIds: ["sub-math-10", "sub-cs-10", "sub-bio-10"],
        studentIds: ["VRTX-STU-0001"],
        mentorTeacherId: "VRTX-TCH-001",
        feeTemplateId: "fee-tpl-g10-north",
      },
    ],
    courses: [
      {
        id: "course-math-10a",
        name: "Mathematics 10A",
        branchId: "branch-north",
        subjectId: "sub-math-10",
        teacherId: "VRTX-TCH-001",
      },
    ],
    grades: [
      {
        studentId: "VRTX-STU-0001",
        courseId: "course-math-10a",
        assessment: "Mid-Term Exam",
        score: 88,
        term: "Fall 2024",
      },
    ],
    feeTemplates: [
      {
        id: "fee-tpl-g10-north",
        branchId: "branch-north",
        name: "Grade 10 Standard Fees",
        amount: 120000,
        gradeLevel: 10,
        monthlyBreakdown: Array(12)
          .fill(0)
          .map((_, i) => ({
            month: new Date(0, i).toLocaleString("default", { month: "long" }),
            total: 10000,
            breakdown: [
              { component: "Tuition", amount: 8000 },
              { component: "Misc", amount: 2000 },
            ],
          })),
      },
    ],
    feeRecords: [
      {
        studentId: "VRTX-STU-0001",
        totalAmount: 120000,
        paidAmount: 80000,
        dueDate: new Date("2025-03-10"),
        previousSessionDues: 5000,
      },
    ],
    auditLogs: [
      {
        id: "log-1",
        userId: "admin-1",
        userName: "Admin User",
        action: 'Approved registration for "South Branch"',
        timestamp: new Date(Date.now() - 3600000 * 1),
      },
      {
        id: "log-2",
        userId: "admin-1",
        userName: "Admin User",
        action: "Updated status for 'North Branch' to suspended",
        timestamp: new Date(Date.now() - 3600000 * 3),
      },
    ],
    principalQueries: [
      {
        id: "pq-1",
        branchId: "branch-north",
        principalId: "principal-1",
        principalName: "Dr. Evelyn Reed",
        schoolName: "North Branch",
        subject: "Billing Discrepancy",
        queryText:
          "We were billed for 150 students but we only have 148 active students this month. Please clarify.",
        submittedAt: new Date(Date.now() - 86400000 * 2),
        status: "Open",
      },
      {
        id: "pq-2",
        branchId: "branch-south",
        principalId: "principal-2",
        principalName: "Mr. Alan Grant",
        schoolName: "South Branch",
        subject: "Feature Request: Canteen Module",
        queryText:
          "It would be great to have a module for managing canteen inventory and daily sales.",
        submittedAt: new Date(Date.now() - 86400000 * 5),
        status: "Resolved",
        adminNotes:
          "Thank you for the suggestion. We have added it to our product roadmap for Q4.",
        resolvedAt: new Date(Date.now() - 86400000 * 3),
        resolvedBy: "Admin User",
      },
    ],
    systemSettings: [
      {
        id: "global",
        defaultErpPrice: 10,
        globalFeatureToggles: { ...ALL_FEATURES },
        loginPageAnnouncement:
          "Welcome to Verticx ERP. Mid-term examinations begin next month.",
      },
    ],
    erpPayments: [
      {
        id: "erp-pay-1",
        branchId: "branch-north",
        amount: 10,
        paymentDate: new Date(
          new Date().getFullYear(),
          new Date().getMonth(),
          5
        )
          .toISOString()
          .split("T")[0],
        transactionId: "VRTX-ERP-MOCK-001",
      },
    ],
  };
  for (const key of ALL_DB_KEYS) {
    db[key] = (mockData as any)[key] || [];
  }
};

initializeMockData();
